set(_CATKIN_CURRENT_PACKAGE "hokuyo_processing")
set(hokuyo_processing_VERSION "0.0.0")
set(hokuyo_processing_MAINTAINER "kyrie <kyrie@todo.todo>")
set(hokuyo_processing_PACKAGE_FORMAT "2")
set(hokuyo_processing_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "urg_node")
set(hokuyo_processing_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(hokuyo_processing_BUILDTOOL_DEPENDS "catkin")
set(hokuyo_processing_BUILDTOOL_EXPORT_DEPENDS )
set(hokuyo_processing_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "urg_node")
set(hokuyo_processing_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "urg_node")
set(hokuyo_processing_TEST_DEPENDS )
set(hokuyo_processing_DOC_DEPENDS )
set(hokuyo_processing_DEPRECATED "")